### PR TITLE
convert to an actual overwrite for compatibility + some other small changes

### PR DESCRIPTION
**Pull request by TropheusJ**
- converted the main mixin to an actual overwrite instead of a head-n-cancel. Other mods injecting to the same place should now be compatible if their mixins are set up well.
- updated required java to 17 in a couple places, as that's what MC needs now
- added QuiltFlower for better decompiled code (`genSourcesWithQuiltflower` task)
- clean up mixins.json, removing redundant blocks

### CODE REVIEW

**Comment by AeiouEnigma** [comment]
Can you articulate the advantage(s) of changing Java compatibility to 17 from 16? The question arose in an earlier PR proposing the same change.

**Comment by TropheusJ** [comment]
it just prevents a line in the log from appearing saying the compat level changed. nothing functionally different. It doesn't matter anyway, since MC requires java 17.

**Review by AeiouEnigma — APPROVED** [review]

**Comment by audaki** [comment]
@TropheusJ have you compiled the plugin with the overwrite and tested it to ensure it works? Need to ask this before I publish the updated plugin. I remember I tried to overwrite some function for this plugin and it caused problems in some function.

@AeiouEnigma thanks for helping <3

**Comment by audaki** [comment]
@TropheusJ I've reverted the PR because the "quiltflower" plugin does not bring any advantage to the users to the mod and adding a maven repository that is very unknown on the internet: https://www.google.com/search?q="server.bbkr.space" is a major security risk. A maven repository is able to deliver the artifacts with viruses, which will then be included in this mod. And then this virus will then run on all users and servers who run this mod...

**Comment by TropheusJ** [comment]
I did test it and it did work.

The [LQF plugin](https://github.com/Juuxel/loom-quiltflower-mini) uses the [QuiltFlower](https://github.com/QuiltMC/quiltflower) decompiler, which are both completely safe. I understand the decision though.

**Comment by TropheusJ** [comment]
I’ll make a new PR with all other changes minus QF once I get a chance.

**Comment by audaki** [comment]
> I’ll make a new PR with all other changes minus QF once I get a chance.

Yes sure! We'll merge it again then and I'll publish the update, thank you!

**Comment by TropheusJ** [comment]
[New PR made](#8), sorry for the trouble.

**Pull request merged**
