### PR TITLE
Fake enable the minecart experiment

### LINKED ISSUE #42: [Feature] Make ACE server-side again
Related to #41.

While I assume it's not explicitly planned, I at least have been using ACE for ages as a server-side only mod to enhance the lackluster vanilla minecart features.

I honestly have not looked into your code to see if I could come up with a solution to restore the server-side functionalities, so I don't know if it's even possible. Maybe [Polymer](polymer.pb4.eu) could be used.

Either way, I'll leave this here as a suggestion, because this mod is usually recommended by many as a server-side enhancement mod for SMPs.

### PR DESCRIPTION
**Pull request by AshyBoxy**
This fixes #42

### CODE REVIEW

**Comment by audaki** [comment]
Wow, nice!

@AshyBoxy Have you tested this in a running server with existing minecarts if this breaks anything? If so I’ll merge it :blush:

**Comment by audaki** [comment]
And I also thought about this approach, but it will cause the server/world to stay on the experiment after the mod is uninstalled, I guess? But I can accept that

**Comment by AshyBoxy** [comment]
The flag is only set when telling the clients what feature flags are enabled, on the logical server it's still disabled. So the actual behaviour of minecarts should be the same as before, and the world is saved without the flag enabled

I've only tested the basic stuff and it seems fine (again, the behaviour should be identical to 4.1.0). I wouldn't know what to look for in complex builds to check if it's broken anyway

**Comment by audaki** [comment]
Ohhh that’s just the spot that sends this info to the client? Then I had a different idea.. This is genius, thank you! :blush:

**Comment by NPC-112** [comment]
Does this mean the marking on modrinth that it is required by clients is no longer true again?

**Comment by audaki** [comment]
@NPC-112 yes, good hint! I’ll change it on modrinth

**Pull request merged**
