### PR TITLE
Update to 1.18.1

### PR DESCRIPTION
**Pull request by tyleraharrison**

### CODE REVIEW

**Comment by TwoPointInfinity** [comment]
If you set the compatibility version to 17 it will be incompatible with the fabric-api. leaving it at 16 does not change anything.

**Comment by tyleraharrison** [comment]
Thats odd, mine works fine

**Comment by TwoPointInfinity** [comment]
I would say that is odd. I mean if it works nvm but every mod I have and have looked at that was set to 17 wouldn't run

**Comment by audaki** [comment]
Heya, Log4j fucked me over.

Does changing compatibility version to 17 have any ADVANTAGE?

**Comment by tyleraharrison** [comment]
I'm not sure, but I've seen it in some Fabric templates. Isn't Java 17 required to run a server now?

**Comment by audaki** [comment]
Heya @tyleraharrison, I've decided to use the other pull request, it seems to be less risky for now :-) Thank you though very much for the pull request!

**Comment by tyleraharrison** [comment]
Sounds good, Log4J killed me too lol I work cybersec

**Pull request closed without merging**
